---
title: "TrisomPlacentos"
author: "Rolandas Porejus"
date: "May 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
source("http://bioconductor.org/biocLite.R")
biocLite("GEOquery")

#Load libraries
library(Biobase)
library(GEOquery)

#Load data from GEO

gset <- getGEO("GSE66210", GSEMatrix =TRUE, getGPL=FALSE)
GPLset <- getGEO("GPL13534", getGPL=TRUE)
```
```{r}
if (length(gset) > 1) idx <- grep("GPL13534", attr(gset, "names")) else idx <- 1
gset2 <- na.omit(gset[[idx]])
assaydata = exprs(gset2)
```

Surušiuojame duomenis ir sukuriame hyper/hipo metilinimo matricas.
```{r}
MBC <- gset2[, gset2$`tissue:ch1` == "maternal whole blood"]
CVS <- gset2[, gset2$`tissue:ch1` == "chorionic villus"]

CVSnorm <- subset(CVS@phenoData@data, `pregnancy:ch1` == 'normal pregnancy')
CVS_T21 <- subset(CVS@phenoData@data, `pregnancy:ch1` == 'trisomy 21')
CVS_T13 <- subset(CVS@phenoData@data, `pregnancy:ch1` == 'trisomy 13')
CVS_T18 <- subset(CVS@phenoData@data, `pregnancy:ch1` == 'trisomy 18')

```

Skaičiuojame kiek iš viso yra metilinimo saitų apibrėžtose grupėse.
```{r}
library(scales)
methyl_vec <- numeric()

means <- rowMeans(MBC@assayData$exprs[,MBC$geo_accession])
means1 <- subset(means, means<0.2)
HypomethylMBC_Num <- NROW(means1)
methyl_vec <- append(methyl_vec, HypomethylMBC_Num)
methyl_vec <- append(methyl_vec, percent(HypomethylMBC_Num/NROW(means)))
means2 <- subset(means, means>0.8)
HypermethylMBC_Num <- NROW(means2)
methyl_vec <- append(methyl_vec, HypermethylMBC_Num)
methyl_vec <- append(methyl_vec, percent(HypermethylMBC_Num/NROW(means)))

means <- rowMeans(CVS@assayData$exprs[,CVSnorm$geo_accession])
means1 <- subset(means, means<0.2)
HypomethylCVSnorm_Num <- NROW(means1)
methyl_vec <- append(methyl_vec, HypomethylCVSnorm_Num)
methyl_vec <- append(methyl_vec, percent(HypomethylCVSnorm_Num/NROW(means)))
means2 <- subset(means, means>0.8)
HypermethylCVSnorm_Num <- NROW(means2)
methyl_vec <- append(methyl_vec, HypermethylCVSnorm_Num)
methyl_vec <- append(methyl_vec, percent(HypermethylCVSnorm_Num/NROW(means)))

means <- rowMeans(CVS@assayData$exprs[,CVS_T21$geo_accession])
means1 <- subset(means, means<0.2)
HypomethylCVS_T21_Num <- NROW(means1)
methyl_vec <- append(methyl_vec, HypomethylCVS_T21_Num)
methyl_vec <- append(methyl_vec, percent(HypomethylCVS_T21_Num/NROW(means)))
means2 <- subset(means, means>0.8)
HypermethylCVS_T21_Num <- NROW(means2)
methyl_vec <- append(methyl_vec, HypermethylCVS_T21_Num)
methyl_vec <- append(methyl_vec, percent(HypermethylCVS_T21_Num/NROW(means)))

means <- rowMeans(CVS@assayData$exprs[,CVS_T13$geo_accession])
means1 <- subset(means, means<0.2)
HypomethylCVS_T13_Num <- NROW(means1)
methyl_vec <- append(methyl_vec, HypomethylCVS_T13_Num)
methyl_vec <- append(methyl_vec, percent(HypomethylCVS_T13_Num/NROW(means)))
means2 <- subset(means, means>0.8)
HypermethylCVS_T13_Num <- NROW(means2)
methyl_vec <- append(methyl_vec, HypermethylCVS_T13_Num)
methyl_vec <- append(methyl_vec, percent(HypermethylCVS_T13_Num/NROW(means)))

means <- rowMeans(CVS@assayData$exprs[,CVS_T18$geo_accession])
means1 <- subset(means, means<0.2)
HypomethylCVS_T18_Num <- NROW(means1)
methyl_vec <- append(methyl_vec, HypomethylCVS_T18_Num)
methyl_vec <- append(methyl_vec, percent(HypomethylCVS_T18_Num/NROW(means)))
means2 <- subset(means, means>0.8)
HypermethylCVS_T18_Num <- NROW(means2)
methyl_vec <- append(methyl_vec, HypermethylCVS_T18_Num)
methyl_vec <- append(methyl_vec, percent(HypermethylCVS_T18_Num/NROW(means)))

```
Sukuriame lentelę
```{r}
methylation <- matrix(methyl_vec,ncol=4,byrow=TRUE)
colnames(methylation) <- c("Number of sites (β<0.2)","Percent (β<0.2)","Number of sites (β>0.8)","Percent (β>0.8)")
rownames(methylation) <- c("MBC","CVSnorm","CVS T21","CVS T13","CVS T18")
methylation <- as.table(methylation)
methylation
```

Rušiuojame pagal CpG tipus
```{r}
Islands <- subset(GPLset@dataTable@table, Relation_to_UCSC_CpG_Island == "Island")
Shores <- subset(GPLset@dataTable@table, Relation_to_UCSC_CpG_Island == "S_Shore" | Relation_to_UCSC_CpG_Island == "N_Shore")
Shelfs <- subset(GPLset@dataTable@table, Relation_to_UCSC_CpG_Island == "S_Shelf" | Relation_to_UCSC_CpG_Island == "N_Shelf")
Open_sea <- subset(GPLset@dataTable@table, Relation_to_UCSC_CpG_Island == "")
```

Tikimybiu tankumo grafikai
Raudona - motinos kraujas (sveikas) 
Mėlyna - sveikos placentos
Juoda - T13 plaentos
Pilka - T18 placentos
Žalia - T21 placentos
```{r}
d <- density(na.omit(c(MBC@assayData$exprs)))
plot(d, main=paste("All (",NROW(MBC@assayData$exprs),")"),xlab="β-value", col="red")
par(new=T)
d <- density(na.omit(c(CVS@assayData$exprs[,CVSnorm$geo_accession])))
plot(d, main ="", col="blue",xlab="",ylab="", xlim=c(0,1))
par(new=T)
d <- density(na.omit(c(CVS@assayData$exprs[,CVS_T13$geo_accession])))
plot(d, main ="", col="black",xlab="",ylab="", xlim=c(0,1))
par(new=T)
d <- density(na.omit(c(CVS@assayData$exprs[,CVS_T18$geo_accession])))
plot(d, main ="", col="grey",xlab="",ylab="", xlim=c(0,1))
par(new=T)
d <- density(na.omit(c(CVS@assayData$exprs[,CVS_T21$geo_accession])))
plot(d, main ="", col="green",xlab="",ylab="", xlim=c(0,1))
par(new=F)

d <- density(na.omit(c(MBC@assayData$exprs[Islands$Name,])))
plot(d, main=paste("Islands (",NROW(MBC@assayData$exprs[Islands$Name,]),")"),xlab="β-value", col="red")
par(new=T)
d <- density(na.omit(c(CVS@assayData$exprs[Islands$Name,CVSnorm$geo_accession])))
plot(d, main ="", col="blue",xlab="",ylab="")
par(new=T)
d <- density(na.omit(c(CVS@assayData$exprs[Islands$Name,CVS_T13$geo_accession])))
plot(d, main ="", col="black",xlab="",ylab="")
par(new=T)
d <- density(na.omit(c(CVS@assayData$exprs[Islands$Name,CVS_T18$geo_accession])))
plot(d, main ="", col="grey",xlab="",ylab="")
par(new=T)
d <- density(na.omit(c(CVS@assayData$exprs[Islands$Name,CVS_T21$geo_accession])))
plot(d, main ="", col="green",xlab="",ylab="")
par(new=F)

```

